#!/usr/bin/env python3
"""Stand up MediaMTX: RTSP in from the camera, HLS out, recording on disk.

WHY MEDIAMTX AND NOT FFMPEG BY HAND
  One process does ingest, browser delivery and recording with retention. An
  ffmpeg pipeline would need three of them plus a supervisor and a cleanup
  cron - three more things to silently stop working.

WHY THE STREAM IS NOT TRANSCODED
  Measured, not assumed: all three channels are H.264, which every browser
  plays natively, so WebRTC/HLS carry it through untouched. CPU stays near
  idle no matter how many people watch.

DELIVERY IS HLS, NOT WEBRTC
  WebRTC needs UDP for ICE and Cloudflare Tunnel carries HTTP. WebRTC would
  work on the LAN and fail for every public viewer - broken in the way that
  passes local testing.

AUDIO
  The camera sends AAC alongside the video and it lands in the 30-day archive.
  Recording audio is treated differently from recording video in most US
  states, and usually more strictly, so it has to be genuinely switchable -
  muting a player is not the same thing as not recording.

  Switching it off is not a MediaMTX flag: it cannot filter tracks from a
  pulled source. So when audio is off the camera is pulled by ffmpeg with
  '-c copy -an' and republished to MediaMTX over loopback RTSP. No re-encode,
  the video is bit-identical, the audio track simply never exists. That is
  why the ffmpeg-bundled image is used.

DISK
  843 GB free at build time; 720p H.264 at 20fps is roughly 16-27 GB/day.
  RETENTION_DAYS leaves headroom, and camera_monitor warns before the disk
  fills rather than after.
"""
import os
import shutil
import subprocess
import sys
from datetime import datetime

BASE = os.path.expanduser("~/network-agent-backup")
CONF = os.path.join(BASE, "config/camera.conf")
SETTINGS = os.path.join(BASE, "config/camera-settings.conf")
CAM_DIR = os.path.join(BASE, "camera")
RECORD_DIR = os.path.expanduser("~/camera-recordings")
TS = datetime.now().strftime("%Y%m%d-%H%M%S")

RETENTION_DAYS = 30
IMAGE = "bluenviron/mediamtx:latest-ffmpeg"

# Channel -> what it is. Measured with ffprobe, not read off the app's display
# order, which lists them lowest-first and would have made 1080 the default
# for every viewer.
CHANNELS = {
    "hd":     ("ch1", "1920x1080"),
    "sd":     ("ch2", "1280x720"),
    "mobile": ("ch3", "640x360"),
}
RECORD_STREAM = "sd"
INTERNAL_RTSP = "127.0.0.1:8554"


def load_conf():
    if not os.path.exists(CONF):
        sys.exit(f"FATAL: {CONF} missing")
    c = {}
    for line in open(CONF):
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            c[k.strip()] = v.strip()
    for k in ("rtsp_user", "rtsp_pass", "rtsp_host"):
        if not c.get(k):
            sys.exit(f"FATAL: {k} missing or empty in {CONF}")
    return c


def record_audio_enabled():
    """Default ON, matching the camera. Absent file means 'as the camera sends'."""
    if not os.path.exists(SETTINGS):
        return True
    for line in open(SETTINGS):
        line = line.strip()
        if line.startswith("record_audio"):
            return line.partition("=")[2].strip().lower() not in ("no", "false", "0", "off")
    return True


def build_yaml(c, with_audio=True):
    user, pw, host = c["rtsp_user"], c["rtsp_pass"], c["rtsp_host"]
    lines = [
        "# GENERATED by setup_mediamtx.py - contains credentials, mode 600,",
        "# gitignored. Edit setup_mediamtx.py and re-run; editing this file",
        "# directly is lost on the next run.",
        f"# audio recording: {'ON' if with_audio else 'OFF'}",
        "logLevel: info",
        "",
        "hls: yes",
        "hlsAddress: 127.0.0.1:8888",
        "hlsVariant: lowLatency",
        "hlsAlwaysRemux: no",
        "webrtc: no",
        "",
        "# EVERY LISTENER BINDS TO LOOPBACK. Binding wider published an",
        "# UNAUTHENTICATED API on the LAN that returns the camera credentials",
        "# in plaintext - anything on the network could read them.",
        "api: yes",
        "apiAddress: 127.0.0.1:9997",
        "playback: yes",
        "playbackAddress: 127.0.0.1:9996",
        "",
        "rtmp: no",
        "srt: no",
        "moq: no",
        "",
    ]

    if with_audio:
        lines += [
            "# Nothing publishes to this server, so the RTSP listener is off.",
            "rtsp: no",
            "",
        ]
    else:
        lines += [
            "# RTSP listener enabled ONLY so the local audio-stripping ffmpeg",
            "# can republish into this server. Loopback, and nothing outside",
            "# this host can reach it.",
            "rtsp: yes",
            f"rtspAddress: {INTERNAL_RTSP}",
            "rtspTransports: [tcp]",
            "",
        ]

    lines.append("paths:")
    for name, (ch, res) in CHANNELS.items():
        rec = name == RECORD_STREAM
        src = f"rtsp://{user}:{pw}@{host}/{ch}"
        lines += [f"  {name}:", f"    # {res}, H.264"]

        if rec and not with_audio:
            # ffmpeg pulls and republishes without the audio track. -c copy so
            # the video is not re-encoded; -an is what actually removes audio.
            lines += [
                "    # audio OFF: pulled by ffmpeg, republished without the",
                "    # audio track. Video is copied, never re-encoded.",
                "    source: publisher",
                "    runOnInit: >-",
                f"      ffmpeg -nostdin -rtsp_transport tcp -i {src}",
                "      -c copy -an -f rtsp",
                f"      rtsp://{INTERNAL_RTSP}/{name}",
                "    runOnInitRestart: yes",
            ]
        else:
            lines += [
                f"    source: {src}",
                # TCP: a fixed LAN hop, so UDP's tolerance for reordering buys
                # nothing while its tolerance for loss becomes artefacts in a
                # recording kept for 30 days.
                "    rtspTransport: tcp",
                # Only dial the camera when someone is watching. It is a small
                # device and three permanent pulls for an idle portal is load
                # it does not need. The recorded path is exempt - it must run
                # whether anyone is watching or not.
                f"    sourceOnDemand: {'no' if rec else 'yes'}",
                "    sourceOnDemandCloseAfter: 30s",
            ]

        if rec:
            lines += [
                "    record: yes",
                # %path is mandatory - mediamtx refuses to start without it.
                "    recordPath: /recordings/%path/%Y-%m-%d/%H-%M-%S-%f",
                "    recordFormat: fmp4",
                # One hour per file: a corrupt segment costs an hour, not a
                # day, without making tens of thousands of files.
                "    recordSegmentDuration: 1h",
                f"    recordDeleteAfter: {RETENTION_DAYS * 24}h",
            ]
    return "\n".join(lines) + "\n"


COMPOSE = f"""# GENERATED by setup_mediamtx.py
services:
  mediamtx:
    image: {IMAGE}
    container_name: mediamtx
    restart: unless-stopped
    # host networking so HLS and the internal RTSP republish both work on
    # loopback; with bridge networking 127.0.0.1 means the container, not
    # this host.
    network_mode: host
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
      - {RECORD_DIR}:/recordings
    environment:
      - TZ=America/Denver
"""


def sh(cmd):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True)


def apply(with_audio=None, restart=True):
    """Regenerate config and (re)start. Returns (ok, detail)."""
    if with_audio is None:
        with_audio = record_audio_enabled()
    c = load_conf()
    os.makedirs(CAM_DIR, exist_ok=True)
    os.makedirs(RECORD_DIR, exist_ok=True)

    yml = os.path.join(CAM_DIR, "mediamtx.yml")
    if os.path.exists(yml):
        shutil.copy(yml, f"{yml}.bak-{TS}")
    fd = os.open(yml, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as f:
        f.write(build_yaml(c, with_audio))

    with open(os.path.join(CAM_DIR, "docker-compose.yml"), "w") as f:
        f.write(COMPOSE)

    if not restart:
        return True, "config written"

    r = sh(f"cd {CAM_DIR} && docker compose up -d")
    if r.returncode != 0:
        return False, (r.stderr or r.stdout)[-400:]

    # 'up -d' is a NO-OP when only a bind-mounted file changed: the container
    # spec is identical, so compose leaves it running - with the old config
    # still loaded in memory. mediamtx reads mediamtx.yml once, at startup.
    # Writing the file is not applying it. Force the restart.
    r = sh("docker restart mediamtx")
    if r.returncode != 0:
        return False, f"restart failed: {(r.stderr or r.stdout)[-300:]}"
    return True, "restarted"


def main():
    with_audio = record_audio_enabled()
    print(f"=== mediamtx (audio recording {'ON' if with_audio else 'OFF'}) ===")

    gi = os.path.join(BASE, ".gitignore")
    existing = open(gi).read() if os.path.exists(gi) else ""
    add = [p for p in ("camera/mediamtx.yml", "camera/*.bak-*",
                       "config/camera-settings.conf") if p not in existing]
    if add:
        with open(gi, "a") as f:
            f.write("\n# mediamtx config embeds camera credentials\n"
                    + "\n".join(add) + "\n")
        print(f"  .gitignore: added {', '.join(add)}")

    ok, detail = apply(with_audio)
    print(f"  {detail}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
