#!/bin/bash
# ============================================================================
# setup_cloudflared.sh - route cam.example.com to the local portal
#
# WHY A TUNNEL AND NOT A PORT FORWARD
#   Neither WAN has a public IP - one sits behind an ISP gateway, the other
#   behind CGNAT. There is no port to forward. cloudflared makes an OUTBOUND
#   connection and Cloudflare hands traffic back down it, which also means no
#   inbound firewall rule and no certificate to renew.
#
# WHAT IS DELIBERATELY NOT EXPOSED
#   Only cam.example.com -> 127.0.0.1:8081, the portal. MediaMTX itself stays on
#   loopback and unreachable: its API returns the camera credentials in
#   plaintext and has no authentication of its own. Everything that reaches
#   video goes through the portal login.
#
#   The catch-all returns 404, so a request arriving with any other Host
#   header gets nothing rather than being quietly routed somewhere.
#
# Idempotent.
# ============================================================================
set -euo pipefail

# Discovered, not hardcoded. A tunnel ID pasted in here is one more literal
# that silently stops matching reality the moment the tunnel is recreated -
# the failure this project keeps finding. Ask cloudflared instead.
TUNNEL_NAME="${TUNNEL_NAME:-cam}"
HOSTNAME_="${HOSTNAME_:-cam.example.com}"

TUNNEL_ID="${TUNNEL_ID:-$(cloudflared tunnel list --output json 2>/dev/null \
    | python3 -c "
import json,sys
name='${TUNNEL_NAME}'
# A live tunnel does NOT have an empty deleted_at - it has Go's zero time,
# '0001-01-01T00:00:00Z'. Testing for falsy skips every live tunnel and
# reports none found, which is confidently wrong rather than merely wrong.
def deleted(t):
    d = (t.get('deleted_at') or '')
    return bool(d) and not d.startswith('0001-01-01')
try:
    for t in json.load(sys.stdin):
        if t.get('name') == name and not deleted(t):
            print(t['id']); break
except Exception:
    pass
")}"

if [ -z "$TUNNEL_ID" ]; then
    echo "FATAL: no tunnel named '${TUNNEL_NAME}'. Create it first:"
    echo "  cloudflared tunnel create ${TUNNEL_NAME}"
    exit 1
fi
echo "  tunnel '${TUNNEL_NAME}' -> ${TUNNEL_ID}"
PORTAL="http://127.0.0.1:8081"
CFDIR="$HOME/.cloudflared"
CONF="$CFDIR/config.yml"
CREDS="$CFDIR/${TUNNEL_ID}.json"

echo "=== cloudflared config ==="
[ -f "$CREDS" ] || { echo "FATAL: credentials file $CREDS not found"; exit 1; }
echo "  credentials: present"

cat > "$CONF" <<EOF
# GENERATED by setup_cloudflared.sh
tunnel: ${TUNNEL_ID}
credentials-file: ${CREDS}

# Long-lived HLS segment requests: give the origin room rather than cutting
# a stream mid-segment. The defaults are tuned for short API calls.
originRequest:
  connectTimeout: 10s
  keepAliveTimeout: 90s
  noHappyEyeballs: true

ingress:
  - hostname: ${HOSTNAME_}
    service: ${PORTAL}

  # Anything else gets nothing. Without this catch-all cloudflared refuses to
  # start, and a permissive one would route unexpected Host headers somewhere
  # real.
  - service: http_status:404
EOF
chmod 600 "$CONF"
echo "  wrote $CONF"

echo
echo "=== validating ==="
cloudflared tunnel ingress validate
echo
cloudflared tunnel ingress rule "https://${HOSTNAME_}/" | sed 's/^/  /'

echo
echo "=== portal reachable locally? (the tunnel is pointless otherwise) ==="
code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 8 "${PORTAL}/login")
echo "  ${PORTAL}/login -> $code"
[ "$code" = "200" ] || { echo "  FAIL: portal not serving; fix that before exposing it"; exit 1; }

echo
echo "=== next, needs root ==="
echo "  sudo cloudflared service install"
echo "  sudo systemctl enable --now cloudflared"
echo
echo "Then https://${HOSTNAME_} should serve the login page."
